### ISSUE TITLE
Allow an array of route paths

### ISSUE THREAD

**Issue by ghost** [adambabik/express-route#1]
I haven't reviewed you code, is there a way to pass and array of route paths. I have my project setup with multiple directories which have one or more route files.

**Comment by adambabik** [comment]
You can pass a directory with routes definition:

``` javascript
var pathToDirWithRoutes = process.cwd() + '/routes';
route(app, pathToDirWithRoutes, {
  sync: true,
  ensureRestriction: function (req, res, next) { ... }
});
```

It's used in [a test file](https://github.com/dreame4/express-route/blob/master/tests/testIndex.js#L24). However, there is no support for an array of route paths.
